### ISSUE TITLE
File Version Control Using Hashing

### ISSUE THREAD

**Issue by pratikj697** [Ayu-hack/Hacktoberfest2024#10]
Create a Python program that simulates a simple version control system using file hashing. The goal is to maintain a version history of files where changes in file content are tracked, and only the modified files are added to the new version. Files with unchanged content (same hash) will not be duplicated.

Requirements:
1. File Hashing:
For each file, compute a SHA-256 hash to determine whether the file content has changed since the last version.
2. Version Control:
Maintain a history of file versions. Only store a new version of a file if its content has changed (i.e., if the hash is different from the last version).
3. Handling Missing Files:
If a file does not exist, skip it and log the error.

Version Display:
Implement a feature to display the stored versions of files.

Can you please assign this task to me under HacktoberFest 2024 @Ayu-hack.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
