### ISSUE TITLE
A file search script

### ISSUE THREAD

**Issue by debojit11** [Ayu-hack/Hacktoberfest2024#11]
A script that searches a folder the user specifies (as well as its subfolders) and creates a list which should include the complete path of each file and also compiles a list of all files types contained in there.
@Ayu-hack  could you please assign me this under the label hacktoberfest

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
