### ISSUE TITLE
Add 2048 Game with AI Bot (HTML, CSS, JavaScript)

### ISSUE THREAD

**Issue by Akm592** [Ayu-hack/Hacktoberfest2024#15]
## Implement 2048 Game with AI Bot (HTML, CSS, JavaScript)

Create a web-based 2048 game with an AI bot player.
![image](https://github.com/user-attachments/assets/be500773-f140-4610-a069-f90747503a08)

### Requirements:
- Functional 2048 game using vanilla JavaScript
- AI bot to play automatically (e.g., using expectiminimax or MCTS)
- Responsive UI with manual and AI play options
- Display score and game statistics

### Deliverables:
- HTML, CSS, and JavaScript files for the game
- README with instructions

### Bonus:
- AI difficulty levels
- Visualize AI decision-making

@Ayu-hack  could you please assign me this under the label hacktoberfest

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
