### ISSUE TITLE
A timer application to boost productivity.

### ISSUE THREAD

**Issue by Rohit-Sharma-RS** [Ayu-hack/Hacktoberfest2024#5]
This app will be used to boost productivity using the popular pomodaro technique.

**Comment by Ayu-hack** [comment]
Assigned.

**Comment by Ayu-hack** [comment]
Please fork it first.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
