### ISSUE TITLE
Adding pac man

### ISSUE THREAD

**Issue by Aditijainnn** [Ayu-hack/Hacktoberfest2024#7]
Add pac man game assign this issue to me under hacktoberfest gssoc ext

**Comment by Ayu-hack** [comment]
Assigned.Please fork it first.

**Comment by Ayu-hack** [comment]
Please consider contributing to this repo:[ https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution](https://github.com/Ayu-hack/GeeksforGeeks-POTD-Solution)
Sorry for the inconvenience, and thank you for your understanding! 🙏
